moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  # 注册所有可用的控制器
  controller_names:
    - dual_arm_controller
    - panda_1_hand_controller
    - panda_2_hand_controller

  dual_arm_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - panda_1_joint1
      - panda_1_joint2
      - panda_1_joint3
      - panda_1_joint4
      - panda_1_joint5
      - panda_1_joint6
      - panda_1_joint7
      - panda_2_joint1
      - panda_2_joint2
      - panda_2_joint3
      - panda_2_joint4
      - panda_2_joint5
      - panda_2_joint6
      - panda_2_joint7
    allowed_execution_duration_scaling: 2.0
    allowed_goal_duration_margin: 1.0
    action_monitor_rate: 20.0

  panda_1_hand_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - panda_1_finger_joint1

  panda_2_hand_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - panda_2_finger_joint1

